version: '3.8'
services:
  python3:
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=unix$DISPLAY
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/'
    volumes:
      - ./src:/root/src
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
